### ISSUE TITLE
pymodbus.console do not start with version 3.7.0

### ISSUE THREAD

**Issue by serioca** [pymodbus-dev/repl#17]
When I try to start pymodbus.console I get the following error message:

ImportError: cannot import name 'ModbusBinaryFramer' from 'pymodbus.transaction' (/Users/sergiobruni/.pyenv/versions/3.12-dev/envs/panarea2/lib/python3.12/site-packages/pymodbus/transaction.py). Did you mean: 'ModbusAsciiFramer'?

**Comment by araneusdiadema** [comment]
Hello, same issue here. I searched the source files a little and found out that "ModbusBinaryFramer" was removed from pymodbus transtaction.py. In previous version 3.6.9 it was present. This change (or error?) is not reflected in repl. I will stick to 3.6.9 for now.

**Comment by alexrudd2** [comment]
Thanks for the report, and sorry for the breakage.  It's good to know REPL has users but it's less-maintained than we'd like.

Yeah, there are at least three breaking changes from `3.6.x` to `3.7.0`.  
(1) the removed `ModbusBinaryFramer`
(2) several classes in the PDU moved.  For instance, `pymodbus.diag_message` -> `pymodbus.pdu.diag_message`.
(3) the framers moved 

I will try to update the code to work with `3.7.x`.  In the meantime, downgrading to `3.6.9` should work fine.

**Comment by dhoomakethu** [comment]
```
❯ pymodbus.console --help
Traceback (most recent call last):
  File "/Users/sanjay/.pyenv/versions/pymodbus3.12/bin/pymodbus.console", line 5, in <module>
    from pymodbus_repl.client.main import main
  File "/Users/sanjay/.pyenv/versions/3.12.0b3/envs/pymodbus3.12/lib/python3.12/site-packages/pymodbus_repl/client/main.py", line 22, in <module>
    from pymodbus_repl.client.mclient import ModbusSerialClient, ModbusTcpClient
  File "/Users/sanjay/.pyenv/versions/3.12.0b3/envs/pymodbus3.12/lib/python3.12/site-packages/pymodbus_repl/client/mclient.py", line 9, in <module>
    from pymodbus.diag_message import (
ModuleNotFoundError: No module named 'pymodbus.diag_message'
```

**Comment by alexrudd2** [comment]
> (2) several classes in the PDU moved. For instance, `pymodbus.diag_message` -> `pymodbus.pdu.diag_message`. (3) the framers moved

**Comment by dhoomakethu** [comment]
@serioca @araneusdiadema Could you please give a try this branch `pymodbus-3.7-changes` and see if that fixes the issue ? Thanks

**Comment by araneusdiadema** [comment]
> @serioca @araneusdiadema Could you please give a try this branch `pymodbus-3.7-changes` and see if that fixes the issue ? Thanks
Hi, I confirm that the changes solved the issue. REPL works for me now.

**Comment by dhoomakethu** [comment]
Thanks for the confirmation @araneusdiadema

**Comment by alexrudd2** [comment]
@dhoomakethu  Nice job with the changes.  Don't forget to release on PyPI.

**Comment by serioca** [comment]
@dhoomakethu @araneusdiadema 

thanks
