### ISSUE TITLE
Cannot use the pymodbus.console because of  a import error

### ISSUE THREAD

**Issue by raphapassini** [pymodbus-dev/repl#22]
After installing pymodbus and repl I'm getting the following error:

```python
Traceback (most recent call last):
  File "/path/to/file/pymodbus.console", line 5, in <module>
    from pymodbus_repl.client.main import main
  File "/path/to/file/.venv/lib/python3.11/site-packages/pymodbus_repl/client/main.py", line 15, in <module>
    from pymodbus.transaction import (
ImportError: cannot import name 'ModbusAsciiFramer' from 'pymodbus.transaction' (/home/raphael/stuff/plc-client/.venv/lib/python3.11/site-packages/pymodbus/transaction.py)
```

**Comment by alexrudd2** [comment]
Does it work with `pymodbus 3.6.x`?

The framers were reworked in `3.7.0` (https://github.com/pymodbus-dev/pymodbus/pull/2358/files) and this repo hasn't been updated to match yet.

**Comment by dhoomakethu** [comment]
Will take a look and update the codebase to be in sync with pymodbus
changes. Thanks

ಗುರು, ನವೆಂ 7, 2024, 05:16 ದಿನಾಂಕದಂದು Alex ***@***.***> ಅವರು
ಬರೆದಿದ್ದಾರೆ:

**Comment by dhoomakethu** [comment]
There are a lot of breaking changes in the upstream pymodbus and for the time being I will be restricting the pymodbus to the last working version.

**Comment by dhoomakethu** [comment]
@raphapassini please give #23 a try
